# contains configuration for our gcloud app engine app

runtime: nodejs18

automatic_scaling:
  max_instances: 1

resources:
  memory_gb: 1

env_variables:
  AMCLOUD: "gcloud"
  #Reese
  APPURL: "https://aerial-rarity-387219.uc.r.appspot.com"
  CLIENTID: "408671005868-ffsmmkum5dkrt3t4hh3uhlkj4q5sqign.apps.googleusercontent.com"
  
  #Krishiv
  # APPURL: "https://thermal-yeti-387219.ey.r.appspot.com"
  # CLIENTID: "545274653748-i42s5n190q3okluuvqsgocidnik1j5g2.apps.googleusercontent.com"
